### ISSUE TITLE
谢谢分享 很好用！ 但貌似发现一个bug

### ISSUE THREAD

**Issue by whe0804** [zsml2016/TextBannerView#2]
用带图的setDatasWithDrawableIcon方法之后 默认内容是居中的。布局文件里的setGravity=left不起作用了。

**Comment by zsml2016** [comment]
之前公司项目需求要添加这个图标并和文字居中，可能对之前功能有点忽略，我有空看一下，谢谢反馈

**Comment by ChessLuo** [comment]
@whe0804 之前公司项目需求要添加这个图标和文字居中，可能对之前功能有点忽略，我今晚修改一下，谢谢反馈
