### ISSUE TITLE
返回页面会有叠字的情况

### ISSUE THREAD

**Issue by daleige** [zsml2016/TextBannerView#5]

**Comment by ChessLuo** [comment]
@DaLeiGe 建议在页面的对应activity或者fragment监听页面的生命周期，使用startViewAnimator() 、stopViewAnimator()这两个方法：
@Override
    protected void onResume() {
        super.onResume();
        tvBanner.startViewAnimator();
    }

、、、、、、

@Override
    protected void onStop() {
        super.onStop();
        tvBanner.stopViewAnimator();
    }
